name: Secret Scan with Gitleaks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  gitleaks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install Gitleaks
        run: go install github.com/gitleaks/gitleaks/v8@latest

      - name: Run Gitleaks
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ~/go/bin/gitleaks detect --verbose --redact --exit-code 1
