name: Secret Scan with Gitleaks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  gitleaks:
    name: Run Gitleaks to detect secrets
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Run Gitleaks scanner
        uses: gitleaks/gitleaks-action@v2
        with:
          args: "--verbose --redact"
